let x="                   ****************************";
let z="                   *       MASAI SCHOOL        *";
let y="****************************************************************";
console.log(x+"\n"+z+"\n"+y);
let name="*     NAME ••  UMARYAR SIDDIQUI  |   SCHOOL •• MASAI SCHOOL    *";        
console.log(name);
let grade="*     GRADE•• 1                  |   SECTION •• C              *";
console.log(grade);
let roolno="*     ROOLNO •• 1212                                        ";
console.log(roolno);
let subject="*            ENGLISH   |    MATH   |   SCIENCE                 *";
console.log(subject);
let number="*              80      |     83    |    89                     *";
console.log(number);
let h="****************************************************************";
console.log(h);
let result="••••••••••••••••••••RESULT•••••••••••••••••••••••••••••••••";
console.log(result);
let passed="••••••••••••••••••••passed•••••••••••••••••••••••••••••••••";
console.log(passed);